// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdqy5XrdRWfEl50wmdmR_JAC4Q0QHHLGU',
    appId: '1:804006038700:web:0fe0f6a96a17a9b1906309',
    messagingSenderId: '804006038700',
    projectId: 'e-commerce-app-36644',
    authDomain: 'e-commerce-app-36644.firebaseapp.com',
    storageBucket: 'e-commerce-app-36644.firebasestorage.app',
    measurementId: 'G-DFCZE3MQGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4PI8LnxySqJP7U4dIL4QfwGzYW8Mgl-4',
    appId: '1:804006038700:android:735c5c9a408d0619906309',
    messagingSenderId: '804006038700',
    projectId: 'e-commerce-app-36644',
    storageBucket: 'e-commerce-app-36644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQD3FbLm7-mXU7kkPYWEfecJfRMo0ve0',
    appId: '1:804006038700:ios:00fa49f61445a4c6906309',
    messagingSenderId: '804006038700',
    projectId: 'e-commerce-app-36644',
    storageBucket: 'e-commerce-app-36644.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuQD3FbLm7-mXU7kkPYWEfecJfRMo0ve0',
    appId: '1:804006038700:ios:00fa49f61445a4c6906309',
    messagingSenderId: '804006038700',
    projectId: 'e-commerce-app-36644',
    storageBucket: 'e-commerce-app-36644.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdqy5XrdRWfEl50wmdmR_JAC4Q0QHHLGU',
    appId: '1:804006038700:web:8f2940fc6584f94a906309',
    messagingSenderId: '804006038700',
    projectId: 'e-commerce-app-36644',
    authDomain: 'e-commerce-app-36644.firebaseapp.com',
    storageBucket: 'e-commerce-app-36644.firebasestorage.app',
    measurementId: 'G-QCNGXYJWWJ',
  );
}
